import React, { useState, useEffect } from 'react';
import { customerService } from '../services/api';
import Notification from '../components/Notification';

export default function Customers() {
  const [customers, setCustomers] = useState([]);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  
  // Notification states
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState('success');

  useEffect(() => {
    fetchCustomers();
  }, []);

  const fetchCustomers = async () => {
    try {
      const response = await customerService.getAll();
      setCustomers(response.data);
    } catch (err) {
      triggerNotification('Could not download client registry from the backend.', 'error');
    }
  };

  const triggerNotification = (msg, type) => {
    setMessage(msg);
    setMessageType(type);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Front-end validation checks
    if (!name.trim() || !email.trim()) {
      triggerNotification('Please complete all inputs before submitting.', 'error');
      return;
    }

    // Basic regex pattern validation for email formatting
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      triggerNotification('Please provide a structurally valid email address.', 'error');
      return;
    }

    try {
      await customerService.create({ name: name.trim(), email: email.trim().toLowerCase() });
      triggerNotification('New customer account registered successfully.', 'success');
      setName('');
      setEmail('');
      fetchCustomers();
    } catch (err) {
      if (err.response && err.response.data && err.response.data.detail) {
        // Displays custom conflict errors generated by our FastAPI unique constraint guards
        triggerNotification(err.response.data.detail, 'error');
      } else {
        triggerNotification('A network error occurred while establishing client registry.', 'error');
      }
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this customer?')) return;
    try {
      await customerService.delete(id);
      triggerNotification('Customer record successfully removed from system.', 'success');
      fetchCustomers();
    } catch (err) {
      triggerNotification('Cannot delete customer. They are currently linked to existing order history.', 'error');
    }
  };

  return (
    <div>
      <h2 style={{ marginBottom: '1.5rem', color: '#1e293b' }}>Customer Relations Registry</h2>
      
      <Notification message={message} type={messageType} onClose={() => setMessage('')} />

      {/* Account Registration Card */}
      <div style={{ background: '#fff', padding: '1.5rem', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '2rem' }}>
        <h3 style={{ marginTop: 0, marginBottom: '1rem', color: '#334155' }}>👤 Register New Client Account</h3>
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', alignItems: 'end' }}>
          <div style={{ flex: '1', minWidth: '200px' }}>
            <label style={labelStyle}>Full Name</label>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} style={inputStyle} placeholder="John Doe" />
          </div>
          <div style={{ flex: '1', minWidth: '200px' }}>
            <label style={labelStyle}>Email Address</label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} style={inputStyle} placeholder="john.doe@example.com" />
          </div>
          <button type="submit" style={{ ...btnStyle, background: '#10b981' }}>Create Account</button>
        </form>
      </div>

      {/* Directory Log Table */}
      <div style={{ background: '#fff', padding: '1.5rem', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
        <h3 style={{ marginTop: 0, marginBottom: '1rem', color: '#334155' }}>Active Client Directory</h3>
        {customers.length === 0 ? (
          <p style={{ color: '#64748b', margin: 0 }}>No customer profiles logged yet.</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ background: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
                <th style={cellStyle}>Customer ID</th>
                <th style={cellStyle}>Full Name</th>
                <th style={cellStyle}>Email Address</th>
                <th style={{ ...cellStyle, textAlign: 'right' }}>Management Actions</th>
              </tr>
            </thead>
            <tbody>
              {customers.map((c) => (
                <tr key={c.id} style={{ borderBottom: '1px solid #e2e8f0' }}>
                  <td style={cellStyle}>{c.id}</td>
                  <td style={{ ...cellStyle, fontWeight: '500' }}>{c.name}</td>
                  <td style={cellStyle}>{c.email}</td>
                  <td style={{ ...cellStyle, textAlign: 'right' }}>
                    <button onClick={() => handleDelete(c.id)} style={deleteBtnStyle}>Remove Account</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

const labelStyle = { display: 'block', fontSize: '0.85rem', fontWeight: '600', color: '#475569', marginBottom: '0.25rem' };
const inputStyle = { width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid #cbd5e1', boxSizing: 'border-box' };
const cellStyle = { padding: '0.75rem', fontSize: '0.95rem' };
const btnStyle = { color: '#fff', padding: '0.55rem 1.2rem', borderRadius: '4px', fontWeight: '600', cursor: 'pointer', border: 'none', height: '38px' };
const deleteBtnStyle = { background: 'none', border: 'none', color: '#ef4444', cursor: 'pointer', fontWeight: '600', fontSize: '0.9rem' };
